name: TetShow
version: 3.0
main: me.tetshow.TetShow
api-version: 1.21

commands:
  tetset:
    description: Set show location
  tetshow:
    description: Start Tet show
  tetstop:
    description: Stop Tet show
  tetreload:
    description: Reload config
