name: TetShow
version: 4.0-PROMAX
main: TetShow
api-version: 1.21
commands:
  fwmenu:
    usage: /fwmenu
  fwstart:
    usage: /fwstart
  fwstop:
    usage: /fwstop
  fwset:
    usage: /fwset
  fwreload:
    usage: /fwreload
