name: TetShow
version: 2.1
main: me.tetshow.TetShow
api-version: 1.21

commands:
  tetshow:
    description: Start Tet show
  tetstop:
    description: Stop Tet show
  tetset:
    description: Set show location
